# fly.toml app configuration file generated for management-wxisjq on 2026-08-02T11:26:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'management-wxisjq'
primary_region = 'ams'
swap_size_mb = 2048

[build]
  dockerfile = 'Dockerfile'

[env]
  APP_ORIGIN = 'https://management-tyen.fly.dev'
  BACKUP_LOOP_ENABLED = '0'
  COOKIE_SECURE = '1'
  DATA_DIR = '/data'

[[mounts]]
  source = 'data'
  destination = '/data'
  initial_size = '10gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
